/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.practica.formas;

/**
 *
 * @author
 */
public class FrmVacaciones extends javax.swing.JFrame {

    /**
     * Creates new form FrmVacaciones
     */
    public FrmVacaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lblTitulo = new javax.swing.JLabel();
        cmbEstados = new javax.swing.JComboBox<>();
        cmbAtractivos = new javax.swing.JComboBox<>();
        lblSeleccionaEstado = new javax.swing.JLabel();
        lblSeleccionaAtractivo = new javax.swing.JLabel();
        lblServicioAdicional = new javax.swing.JLabel();
        spr = new javax.swing.JSeparator();
        btnAutobus = new javax.swing.JRadioButton();
        btnAvion = new javax.swing.JRadioButton();
        btnAutoPropio = new javax.swing.JRadioButton();
        btnAutoRentado = new javax.swing.JRadioButton();
        lblFormaViaje = new javax.swing.JLabel();
        chkDesayuno = new javax.swing.JCheckBox();
        chkTour = new javax.swing.JCheckBox();
        chkLavanderia = new javax.swing.JCheckBox();
        chkGuarderia = new javax.swing.JCheckBox();
        chkCajaFuerte = new javax.swing.JCheckBox();
        chkDespertador = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta para Vacaciones");
        setMinimumSize(new java.awt.Dimension(800, 600));

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTitulo.setText("Selección de Destinos Turísticos");

        cmbEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbAtractivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSeleccionaEstado.setText("Selecciona el Estado");

        lblSeleccionaAtractivo.setText("Selecciona el Atractivo Turístico");

        lblServicioAdicional.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblServicioAdicional.setText("Servicios Adicionales en tu Estancia");

        lblFormaViaje.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFormaViaje.setText("¿Cómo piensas viajar?");

        chkDesayuno.setText("jCheckBox1");

        chkTour.setText("jCheckBox2");

        chkLavanderia.setText("jCheckBox3");

        chkGuarderia.setText("jCheckBox4");

        chkCajaFuerte.setText("jCheckBox5");

        chkDespertador.setText("jCheckBox6");

        btnRegistrar.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spr, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitulo)
                            .addComponent(cmbEstados, 0, 498, Short.MAX_VALUE)
                            .addComponent(cmbAtractivos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblSeleccionaEstado)
                        .addComponent(lblSeleccionaAtractivo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAutobus)
                            .addGap(64, 64, 64)
                            .addComponent(btnAvion)
                            .addGap(69, 69, 69)
                            .addComponent(btnAutoPropio)
                            .addGap(70, 70, 70)
                            .addComponent(btnAutoRentado))
                        .addComponent(lblFormaViaje)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(chkTour)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkGuarderia))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(chkDesayuno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkLavanderia))
                                .addComponent(lblServicioAdicional, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chkCajaFuerte)
                                .addComponent(chkDespertador)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addComponent(lblSeleccionaEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblSeleccionaAtractivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAtractivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(spr, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFormaViaje)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutobus)
                    .addComponent(btnAvion)
                    .addComponent(btnAutoPropio)
                    .addComponent(btnAutoRentado))
                .addGap(37, 37, 37)
                .addComponent(lblServicioAdicional)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDesayuno)
                    .addComponent(chkLavanderia)
                    .addComponent(chkCajaFuerte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTour)
                    .addComponent(chkGuarderia)
                    .addComponent(chkDespertador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVacaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAutoPropio;
    private javax.swing.JRadioButton btnAutoRentado;
    private javax.swing.JRadioButton btnAutobus;
    private javax.swing.JRadioButton btnAvion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkCajaFuerte;
    private javax.swing.JCheckBox chkDesayuno;
    private javax.swing.JCheckBox chkDespertador;
    private javax.swing.JCheckBox chkGuarderia;
    private javax.swing.JCheckBox chkLavanderia;
    private javax.swing.JCheckBox chkTour;
    private javax.swing.JComboBox<String> cmbAtractivos;
    private javax.swing.JComboBox<String> cmbEstados;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblFormaViaje;
    private javax.swing.JLabel lblSeleccionaAtractivo;
    private javax.swing.JLabel lblSeleccionaEstado;
    private javax.swing.JLabel lblServicioAdicional;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSeparator spr;
    // End of variables declaration//GEN-END:variables
}
